### ISSUE TITLE
Inherit from text-mode?

### ISSUE THREAD

**Issue by jabirali** [kaorahi/howm#11]
Usually, I prefer to truncate lines when editing source code (since code lines should be short, and wrapped lines can be very confusing in e.g. Python code). However, I prefer to wrap lines at word boundaries when editing prose (Org, MarkDown, LaTeX, etc.), since most people I work with use the "one paragraph per line" convention. This is easy to setup:
```emacs-lisp
(setq-default truncate-lines t)
(add-hook 'text-mode-hook 'visual-line-mode)
```
In addition, I like to turn on either [adaptive-wrap](https://elpa.gnu.org/packages/adaptive-wrap.html) or [org-indent-mode](https://orgmode.org/manual/Org-Indent-Mode.html) so that e.g. lists render correctly with wrapped lines.

However, my `text-mode-hook` doesn't apply to the Howm preview buffer, so I can only see the first few words in a note with long lines until i click `RET` to fully open it. I managed to get the behavior I wanted as follows:
```emacs-lisp
(add-hook 'howm-view-contents-mode-hook 'visual-line-mode)
```
Alternatively, you can add `:hook (howm-view-contents-mode . visual-line-mode)` to a `use-package` declaration.

But perhaps it would make sense for `howm-view-contents-mode` to either inherit from `text-mode`, or apply the `text-mode` hooks in its buffer, so that the same view settings that are used for plaintext files, markdown files, etc. apply to the preview buffer? Most likely, all users are using some mode derived from `text-mode` to write their notes, so this might make the notes look more similar during preview and editing.

**Comment by jabirali** [comment]
Thanks! I tested it a bit now, and it seems to work well for me.

**Comment by kaorahi** [comment]
I'll test it myself for a month or so before merging it into the master branch.

**Comment by jabirali** [comment]
Just thought to mention that I’ve been using this for about a week now, and haven’t noticed any regressions yet. So it seems stable to me :)

**Comment by kaorahi** [comment]
Thanks for the feedback. I'd like to proceed carefully with this matter, as backward compatibility is crucial for existing users in long-standing projects.

**Comment by kaorahi** [comment]
ver2. This should be safer. In the previous version, we lose the highlights in the summary buffer by `T` key.

https://github.com/kaorahi/howm/tree/for11_textmode2
