### ISSUE TITLE
Better screenshots

### ISSUE THREAD

**Issue by kaorahi** [kaorahi/howm#13]
* Replace the ugly screenshots on the [project's homepage](https://kaorahi.github.io/howm/). No need for a one-to-one match with the original. (doc/index.html)
* Add screenshots to the [Github page](https://github.com/kaorahi/howm). (README.md)

**Comment by jabirali** [comment]
Perhaps a decent starting point, serving as a mix of a screenshot and an "infomercial" for the linking system in Howm? (Here, using [this integration](https://github.com/protesilaos/modus-themes/issues/117#issuecomment-2337993946) between Howm and the Modus themes.)
<img width="1280" alt="Screenshot 2024-09-18 at 15 03 41" src="https://github.com/user-attachments/assets/06fd3853-af3b-4358-9235-bcbadbb23091">


Perhaps something similar could be done to show the integration between the menu and reminder system? I mainly use Howm for knowledge management, and not for task management so perhaps someone else can assist to best showcase how they use the reminder system :)

**Comment by kaorahi** [comment]
Thank you for the neat screenshot. I really like it and would like to use it for the project, if that's okay for you. We can also add a link to the color settings for convenience, like '<a href="https://github.com/protesilaos/modus-themes/issues/117#issuecomment-2337993946">Color scheme: Modus themes</a>'.

**Comment by jabirali** [comment]
Sure, I would be happy for this to be used to showcase Howm :). I also think it’s a good idea to include a link to the Modus themes as you suggested next to the screenshots, so that users can easily replicate the look that is presented.

**Comment by kaorahi** [comment]
Done. (#14)
