### ISSUE TITLE
Unbinding C-h?

### ISSUE THREAD

**Issue by jabirali** [kaorahi/howm#15]
It seems that Howm binds the `C-h` keyboard shortcut by default in several places (menu and riffle). This, I think, can be quite confusing for new users (it was for me initially):

When learning a new mode, I usually refer to `C-h m` to list all keybindings that the mode defines, `C-h v` to search through customization variables the mode defines, or `C-h k` to see the documentation of a keybinding in case something confusing just happened. This is also mentioned in the Emacs tutorial:

> To use the Help features, type the C-h character, and then a
character saying what kind of help you want.  If you are REALLY lost,
type C-h ? and Emacs will tell you what kinds of help it can give.

To make it easier to adopt Howm for new users, I think perhaps the `C-h` bindings should be disabled in the default configuration. One simple way to do this would be to just revise the quickstart `use-package` instructions to explicitly unmap the `C-h` bindings, so that there is no impact on long-term Howm users that might have gotten used to this keybinding. An alternative would be to add a new customization variable like e.g. `howm-want-C-h-bindings` which can be used to easily turn this on and off, so that only one line of code would be required to toggle these bindings. Setting this to `nil` by default would be friendlier to new users, but setting it to `t` by default would be less confusing for long-time users.

What do you think?

**Comment by kaorahi** [comment]
I think we can simply remove C-h from our keymaps.

I usually try to maintain backward compatibility as much as possible, but in this case, the default C-h binding feels outdated. It was originally intended for scrolling with the SPC/BS pair in very old emacs. Today, it's unnecessary in window systems and doesn't work in terminals by default. So I conclude that no one actually relies on the default C-h binding.

(After `normal-erase-is-backspace` was introduced in emacs, the correct key is no longer C-h but C-? to get SPC/BS working in terminals. I don't think it's worth fixing this at this point, especially with the risk of unintended side effects.)

**Comment by jabirali** [comment]
That makes sense. I agree that in that case it's better to just remove the `C-h` bindings.

For terminals, there are better solutions these days to get proper support for keybindings, e.g. [kkp.el](https://github.com/benjaminor/kkp) and [term-keys](https://github.com/CyberShadow/term-keys). Using Emacs in a modern terminal like e.g. Kitty or iTerm2, I find that backspace (`DEL`), `C-h`, and `C-?` are correctly reported as independent key chords. I think even `xterm` can do this if you use `term-keys` to enable the `modifyOtherKeys` setting but I didn't test.

So from Howm's perspective I think we can say that it is now the responsibility of a modern terminal emulator – possibly with a support package like `term-keys` – to correctly report keys to Emacs.

**Comment by kaorahi** [comment]
Thx for the suggestion. At least, I'll remove C-h in the next update. I may also add (kbd "DEL") instead.

I noticed that special-mode and gnus-summary-mode bind `\C-?` and `\177` for backward scrolling, so I expect binding DEL is quite standard and harmless.

**Comment by jabirali** [comment]
Yes, I'm quite sure I've seen binding backspace as scroll up before. When I click `C-h i` in Emacs to bring up `M-x info`, and then `C-h m` to bring up `M-x describe-mode`, then I find this:
```
Moving within a node:
SPC	Normally, scroll forward a full screen.
	  Once you scroll far enough in a node that its menu appears on the
	  screen but after point, the next scroll moves into its first
	  subnode.  When after all menu items (or if there is no menu),
	  move up to the parent node.
DEL	Normally, scroll backward.  If the beginning of the buffer is
	  already visible, try to go to the previous menu entry, or up
	  if there is none.
```
So if even the Emacs info browser maps `DEL` to scroll up, I think this is a safe default binding for read-only situations.
