### ISSUE TITLE
Some questions to understand correct usage or interpretation of reminders, todos, deferred dates … 

### ISSUE THREAD

**Issue by smartmic** [kaorahi/howm#3]
I'm still having trouble setting up the reminders so that they work as expected. But maybe my understanding is still all wrong. I thought the "deferred"(~) entries were treated the same as reminders, except that they come up periodically (with period length as specified). But the current view of the reminder list makes no sense to me.

This is my exemplary input:

```
[2024-01-22]- Birthday Z - it's in the past
[2024-02-11]- Birthday A
[2024-02-20]+ Todo Item B
[2024-03-15]- Remind me C
[2024-04-30]~365 Yearly check D
[2024-10-01]~365 Yearly check E
[2024-02-15]~60 Bi-monthly activity F
[2024-03-10]- Yet another reminder G
[2024-02-12]+ Todo I
```
and this is how it is displayed in the menu (priority shown for debugging):
![image](https://github.com/kaorahi/howm/assets/6379140/0b5df80c-522f-4343-bafd-a9c2d3a13616)

Now I have the following questions:

* Why are deferred prioritized higher than reminders or todos, even though they are far in the future in terms of date?
* Or why is there hardly any differentiation on the low ranks? Since I see all entries, it is relevant what order they are in, isn't it?
* Now the reminder from January 2024 has been around for a while, but is still ranked number 1 and closer todos or reminders slide over the deferred entries.
* Anniversaries seem to make more sense to tag as scheduled(@) entries, then they appear in the upper block in time (even if they are actually reminders). Is this the recommended practice?

**Comment by kaorahi** [comment]
There seems to be some confusion regarding the interpretation of the specified date. For example, `[2024-02-xx]+` means "hide this item until 2024-02-xx". This also applies for `-` and `~`.

In the present case, all the future items are buried at the "bottom" of the list. The order among these "bottom" items is meaningless.

Furthermore, the name "reminder" might be misleading for the actual purpose of "~". It is typically used for occasionally remembering ideas, for example, things I want to do someday but can't do right now. So its period is just a rough interval. For strict yearly alarms, I simply duplicate "@" or "!" as follows:

```
* [2024-02-xx]!30 Buy Foo's birthday present
* [2025-02-xx]!30 Buy Foo's birthday present
* [2026-02-xx]!30 Buy Foo's birthday present
* [2027-02-xx]!30 Buy Foo's birthday present
```

For tips, refer to TASK MANAGEMENT section in https://github.com/Emacs101/howm-manual for a convenient method to make such periodic copies.

**Comment by smartmic** [comment]
Many thanks for this clarification, @kaorahi, and sorry for my beginner's question, but I have just started to use howm. 

Although I read the howm manual (a really great resource, thx @Emacs101 !), I was a bit confused about the roles of `-`, `+` and `~` types in my beginner's practice and still short list of dates . But your answer makes perfect sense, especially this statement: 

> For example, [2024-02-xx]+ means "hide this item until 2024-02-xx". This also applies for - and ~.

Maybe it can be added to a future version of the manual?

Anyhow, this means, I will  rely more on `@` and `!` items also for general reminders and todos and see where the other types fit better.

Finally, let me say thank you for this great program, I am glad to have discovered it and look forward to continuing to use it!

**Comment by Emacs101** [comment]
> Maybe it can be added to a future version of the manual?

Hi @smartmic! A new edition of the manual is now available. Thanks for catching the issues in the material presentation.

**Comment by smartmic** [comment]
I just read the updated chapter about the time/task management concept, thanks for the update!

It's great, not too short or too long and easy to understand. Especially the visualization in graphs is very helpful (as the saying goes: a picture is worth a thousand words) and completes my understanding of the concept perfectly. And this is really unique, I am happy to have found such a sophisticated task management system in Howm. And I haven't even talked about the notes yet... so many kudos to you @kaorahi @Emacs101 , I think the combination with the modern manual helps beginners like me enormously and could lead to greater popularity - it would be well deserved!
